### ISSUE TITLE
Stop daemon after period of inactivity

### ISSUE THREAD

**Issue by secrettriangle** [typicode/katon#58]
Would be great if katon could optionally automatically stop a daemon if it hasn't been accessed in a while (perhaps some user-configurable duration).

**Comment by typicode** [comment]
Glad you talk about it.
It's a feature that existed in version prior to 0.9.0, I just forgot to put it back after I've rewrote katon router :sweat_smile:

**Comment by typicode** [comment]
Should be good now `v0.9.1` :)
They are stopped after 1 hour if no requests are made.
