### ISSUE TITLE
Configure 4 second timeout on app load...

### ISSUE THREAD

**Issue by TylerGarlick** [typicode/katon#76]
The ability to set a custom timeout that's greater than 4 seconds.

**Comment by ikido** [comment]
+1 for this, it doesn't work well for rails projects served by webrick

**Comment by typicode** [comment]
@TylerGarlick @ikido thanks for the feedback.

I think the default timeout could be increased. What would be a good timeout? How long does webrick takes to start approximatively?

**Comment by ikido** [comment]
@typicode It takes 8 seconds for my average app, guess startup time depends on many factors so config option would be great. Anyway, thanks for a great tool — switched to Katon from Anvil because it allows to run all my Node and Rails apps. Missing OSX menubar item though)

**Comment by typicode** [comment]
I've increased the default value to ~10 seconds. This way it'll cover a wider range of servers out of the box and give a better first experience to Rails users :)

If you have servers that need more just let me know and I'll look into something configurable.

BTW, if you're doing development on other platforms than OS X, I'm working on [hotel](https://github.com/typicode/hotel) and would be interested in user feedback.
